import { Sidebar } from "@/components/ui/side-bar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const WALLETS_MOCK = [
  {
    id: "7ca93b7d-262e-4088-be49-9463d5ce4281",
    name: "Shorts",
  },
  {
    id: "d2e8c351-cc93-4d85-b4f1-771cde257587",
    name: "DCA",
  },
  {
    id: "1caeb159-18a2-49fa-85cb-2a952f32bc0c",
    name: "Holding",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" class="dark">
      <div className="grid lg:grid-cols-5">
        <Sidebar className="hidden lg:block" wallets={WALLETS_MOCK} />
        <div className="p-8">{children}</div>
      </div>
    </html>
  );
}
